### PR TITLE
Create Selenium_Framework

### PR DESCRIPTION
**Pull request by rengaswa-dv**
# Need Review

### CODE REVIEW

**Comment by mohamedismail86** [comment]
InProgress

**Comment by mohamedismail86** [comment]
Please add the comments in headers

**Comment by rengaswa-dv** [comment]
Based on your comments, I have added the Headers in it and change the package name in my code.
Please review the changes and let me know.

**Comment by mohamedismail86** [comment]
Looks good to me. Ok to Merge

**Comment by rengaswa-dv** [comment]
Thanks for your review.

**Comment by mohamedismail86** [comment]
I’m in progress.

**Pull request merged**
